--100 records
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (1,'Rooney','Cabrera','Other','AB+','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (2,'Gannon','Wolfe','Female','A+','Stomachache',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (3,'Graiden','Walls','Other','A-','Gastric, Constapation, Cold, Fever',1,'Blue Cross Blue Shield');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (4,'Jade','Morin','Female','AB+','Headache, Cold, Chest Pain, Cough',1,'Kaiser Permanente');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (5,'Aquila','Yates','Other','A-','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (6,'Sarah','Keller','Other','AB-','Fever, Cold, Constapation, Headache',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (7,'Carly','Pruitt','Female','B+','Gastric',1,'Cigna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (8,'McKenzie','Barber','Female','O+','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (9,'Keaton','Wade','Other','O-','Gastric, Chest Pain, Fever, Stomachache',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (10,'Mannix','Stanley','Male','A+','Chest Pain, Gastric',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (11,'Walter','Hooper','Other','O-','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (12,'Dara','Head','Male','A+','Gastric, Chest Pain, Constapation',1,'Blue Cross Blue Shield');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (13,'Brett','Marshall','Other','O-','Gastric, Headache, Fever',1,'Kaiser Permanente');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (14,'Leilani','Snyder','Other','AB-','',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (15,'Alma','Rodriquez','Male','B+','Cough, Cold',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (16,'Martena','Lamb','Female','A-','Gastric, Cold, Cough',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (17,'Tad','Curry','Other','B+','',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (18,'Ava','Mooney','Other','A-','Stomachache, Cold, Constapation, Gastric',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (19,'Macey','Buck','Other','AB-','Stomachache, Constapation',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (20,'Hop','Wolfe','Male','B-','Constapation, Cough',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (21,'Dorian','Schmidt','Male','B-','Cough',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (22,'Josiah','Harrison','Other','AB-','Cold',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (23,'Xerxes','Woods','Other','AB+','Headache, Chest Pain',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (24,'Haley','Franklin','Male','AB-','Gastric, Stomachache',1,'Anthem');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (25,'Jenette','Greene','Male','B+','Constapation, Cold',1,'Kaiser Permanente');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (26,'Martina','Estes','Female','A+','Cold, Chest Pain, Constapation, Headache',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (27,'Idona','Nguyen','Female','A+','Gastric, Headache, Constapation, Fever',1,'Cigna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (28,'Walter','Gill','Female','B+','Cold',1,'Blue Cross Blue Shield');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (29,'Yvonne','Tanner','Female','A-','',1,'Anthem');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (30,'Alan','Walker','Other','O+','Cough, Fever, Headache',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (31,'Neil','Orr','Other','A-','',1,'Aetna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (32,'Delilah','Battle','Other','B-','Cold, Fever, Headache, Constapation',1,'Kaiser Permanente');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (33,'Paki','Gibson','Female','B+','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (34,'Keane','Cameron','Male','AB-','Stomachache, Fever',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (35,'Igor','Hoover','Female','O-','Gastric, Stomachache, Constapation, Headache',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (36,'Meghan','Knowles','Other','AB-','',1,'Blue Cross Blue Shield');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (37,'Ian','Wilder','Female','AB-','Headache, Stomachache',1,'Kaiser Permanente');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (38,'Ruby','Pace','Male','A+','Chest Pain',1,'Aetna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (39,'Nathan','Ware','Female','B-','Chest Pain, Headache',1,'Cigna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (40,'Dacey','Duke','Male','AB+','Headache',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (41,'Malik','Church','Female','O+','Headache, Stomachache, Fever',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (42,'Fredericka','Mclean','Male','AB-','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (43,'Quinn','Byrd','Other','A+','Cough, Stomachache',1,'Cigna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (44,'Germaine','Meyer','Other','A-','Constapation, Gastric, Headache, Fever',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (45,'Kenneth','Buck','Other','B-','Headache',1,'Blue Cross Blue Shield');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (46,'Baker','Singleton','Other','AB-','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (47,'Joshua','Coffey','Female','B+','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (48,'Deirdre','Rose','Female','A+','Gastric, Constapation',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (49,'Paula','James','Male','O+','Headache, Constapation',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (50,'Baxter','Durham','Other','A+','Constapation, Fever',1,'Anthem');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (51,'Chelsea','Wise','Female','AB-','Headache',1,'Blue Cross Blue Shield');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (52,'Cassandra','Holloway','Other','A+','Headache, Fever, Gastric',1,'Cigna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (53,'Eve','Knight','Male','A-','Constapation',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (54,'Blaine','Carver','Other','AB-','Constapation, Fever, Cold',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (55,'Georgia','Chan','Other','O-','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (56,'Darius','Henderson','Female','B+','Fever, Cough, Headache',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (57,'Quinn','Wooten','Other','O+','Cough, Constapation, Gastric, Chest Pain',1,'UHG');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (58,'Hedy','Griffith','Male','AB-','Gastric',1,'Kaiser Permanente');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (59,'Cole','Huffman','Female','B-','',1,'Anthem');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (60,'Olivia','Rosales','Male','AB-','Chest Pain, Stomachache, Constapation',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (61,'Ali','Hickman','Male','A+','',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (62,'Richard','Strong','Female','O-','Cold, Chest Pain, Gastric',1,'UHG');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (63,'Jerome','Kelly','Female','AB+','',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (64,'Cora','Donaldson','Female','B-','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (65,'Hilary','Gibson','Other','B+','Headache',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (66,'Kelly','Burks','Other','AB+','Headache',1,'UHG');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (67,'Gloria','Nelson','Female','A-','',1,'Blue Cross Blue Shield');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (68,'Colorado','Saunders','Male','B-','Fever, Cough, Stomachache, Cold',1,'Blue Cross Blue Shield');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (69,'Caldwell','Mckay','Female','B+','Cold',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (70,'Kyle','Dixon','Other','AB+','Constapation, Stomachache, Cold, Chest Pain',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (71,'Raya','Wood','Male','A-','Gastric, Headache',1,'Aetna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (72,'Macey','Beach','Male','AB+','Headache, Fever, Gastric, Constapation',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (73,'Mari','Randall','Male','AB-','Constapation, Gastric, Fever, Stomachache',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (74,'Amena','Howell','Female','O+','Constapation, Headache',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (75,'Reuben','Branch','Other','B+','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (76,'Wesley','Hebert','Male','B-','Constapation, Fever, Headache',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (77,'Wing','Morrow','Male','O+','Fever, Cough',1,'Blue Cross Blue Shield');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (78,'Jasper','Shepherd','Other','B-','Cold, Stomachache, Gastric',1,'Kaiser Permanente');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (79,'Melyssa','Nash','Other','AB+','Gastric',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (80,'Cheyenne','Wiggins','Female','O-','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (81,'Reece','Nunez','Other','B+','',1,'Cigna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (82,'Hashim','Sloan','Female','A-','Stomachache, Constapation',1,'UHG');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (83,'Selma','Melendez','Male','O-','Cough, Fever',1,'Blue Cross Blue Shield');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (84,'Joseph','Hines','Male','O-','Chest Pain, Fever, Constapation, Headache',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (85,'Avye','Stuart','Male','AB-','Gastric',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (86,'Maggy','Morse','Female','B+','Cold, Fever',1,'Aetna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (87,'Madeson','Gregory','Female','O-','Cold, Fever, Chest Pain',1,'UHG');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (88,'Renee','Gallegos','Other','O-','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (89,'Arden','Robertson','Male','B-','Cold, Chest Pain',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (90,'Ronan','Moran','Male','A-','Headache, Cough',1,'Humana');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (91,'Keegan','Marks','Other','AB+','Cough',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (92,'Tad','Grimes','Other','AB-','Headache, Fever, Cough',1,'Anthem');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (93,'Virginia','Brady','Female','AB-','Cough',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (94,'Imelda','Kirkland','Other','B-','Headache, Cough',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (95,'Octavius','Waters','Male','AB-','Cold',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (96,'Amela','Conner','Female','AB+','Cough, Gastric',1,'Aetna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (97,'Chanda','Sargent','Female','O+','',0,NULL);
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (98,'Ralph','May','Other','B-','Chest Pain',1,'Anthem');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (99,'Lenore','Lowery','Male','B+','Cold, Headache, Gastric',1,'Aetna');
INSERT INTO patient (patient_id,first_name,last_name,gender,blood_group,current_condition,insurance_covered,insurance_name) VALUES (100,'Adrienne','King','Male','O+','',0,NULL);

--update insurance_name to NULL when insurance_covered is NO
--and re-populate the inserts
