--100 records
INSERT INTO patient (patient_id,name,gender,current_condition,blood_group) VALUES (1,"Evan","Male","","B-"),(2,"Garrett","Female","Cough, Chest Pain, Constapation","A+"),(3,"Blair","Female","Stomachache, Cough, Cold","AB+"),(4,"Brenna","Male","Fever","O+"),(5,"Honorato","Female","Cough, Constapation, Cold, Fever","A-"),(6,"Margaret","Male","Constapation, Gastric","AB+"),(7,"Chanda","Female","Headache","AB-"),(8,"Ruth","Female","Fever, Chest Pain","AB+"),(9,"Keefe","Female","","B-"),(10,"Hope","Other","Gastric, Headache, Constapation","O-");
INSERT INTO patient (patient_id,name,gender,current_condition,blood_group) VALUES (11,"Beau","Other","Gastric, Headache","O+"),(12,"Fitzgerald","Female","","O+"),(13,"Claire","Male","Constapation, Fever","B+"),(14,"Sydnee","Female","Cold, Chest Pain, Gastric","AB-"),(15,"Jescie","Female","","A-"),(16,"Denton","Female","Gastric, Cold","B-"),(17,"Marshall","Other","Gastric, Constapation, Headache, Fever","A-"),(18,"Lamar","Other","Cold, Chest Pain, Cough","B+"),(19,"Macy","Other","Chest Pain, Fever, Cough, Cold","A-"),(20,"Acton","Female","Chest Pain, Fever","O-");
INSERT INTO patient (patient_id,name,gender,current_condition,blood_group) VALUES (21,"Avye","Other","Stomachache, Gastric","AB-"),(22,"Garrison","Female","","A-"),(23,"Kirsten","Male","Stomachache, Gastric","O-"),(24,"Hammett","Female","","O-"),(25,"Mannix","Female","Headache, Cough","AB+"),(26,"Nelle","Other","Gastric, Stomachache, Cold, Headache","O-"),(27,"Cameron","Other","Constapation, Cough, Cold, Headache","O-"),(28,"Garrett","Female","Cough, Stomachache, Gastric","O-"),(29,"Daquan","Other","Fever, Stomachache","O-"),(30,"Barry","Male","Cold, Cough, Chest Pain, Stomachache","B+");
INSERT INTO patient (patient_id,name,gender,current_condition,blood_group) VALUES (31,"Melvin","Male","Cold, Gastric, Chest Pain, Cough","O-"),(32,"Cynthia","Male","Gastric, Headache","B-"),(33,"Burton","Other","Cold, Stomachache","AB-"),(34,"Desirae","Male","Chest Pain, Headache","AB-"),(35,"Kitra","Male","Gastric, Constapation, Stomachache, Cough","O-"),(36,"Fuller","Female","Cough, Fever, Headache, Chest Pain","AB+"),(37,"Noelani","Other","Headache, Constapation, Cold","A-"),(38,"Brady","Male","Chest Pain, Gastric, Headache","O+"),(39,"Uriah","Other","Stomachache, Constapation, Cough","B-"),(40,"Joelle","Female","Cold","A-");
INSERT INTO patient (patient_id,name,gender,current_condition,blood_group) VALUES (41,"Lev","Other","Gastric","A-"),(42,"Iliana","Male","Chest Pain","O+"),(43,"Kermit","Male","Headache","B+"),(44,"Blaze","Female","","AB-"),(45,"Imelda","Male","Fever","AB-"),(46,"Alexa","Other","Cold, Fever, Headache","B-"),(47,"Leila","Male","Headache, Gastric, Fever, Chest Pain","A+"),(48,"Juliet","Other","Headache","O-"),(49,"Brendan","Male","Chest Pain, Constapation, Fever, Stomachache","AB+"),(50,"Doris","Female","Stomachache, Gastric","AB+");
INSERT INTO patient (patient_id,name,gender,current_condition,blood_group) VALUES (51,"Wesley","Male","Chest Pain, Constapation, Headache","B+"),(52,"Akeem","Female","Stomachache, Fever, Constapation, Chest Pain","A-"),(53,"Emery","Female","","A+"),(54,"Gail","Female","Cold, Fever, Constapation, Stomachache","B+"),(55,"Gay","Other","Headache, Chest Pain","B-"),(56,"Noelle","Other","Stomachache, Constapation, Fever, Chest Pain","B-"),(57,"Victor","Female","Cough, Chest Pain, Stomachache","O+"),(58,"Jesse","Other","Cough, Stomachache","AB+"),(59,"Savannah","Female","","B-"),(60,"Akeem","Other","Cold, Fever, Headache","O+");
INSERT INTO patient (patient_id,name,gender,current_condition,blood_group) VALUES (61,"Grady","Male","Fever, Cough","B+"),(62,"Timothy","Other","","O+"),(63,"Dieter","Male","Cold, Stomachache, Gastric","AB-"),(64,"Piper","Female","Headache, Fever","B-"),(65,"Honorato","Male","","O-"),(66,"Latifah","Other","Chest Pain, Constapation, Cold","A+"),(67,"Suki","Female","","AB+"),(68,"Perry","Female","Cough, Constapation, Chest Pain","A-"),(69,"Cally","Female","","AB+"),(70,"Travis","Other","Constapation, Gastric, Headache, Fever","A+");
INSERT INTO patient (patient_id,name,gender,current_condition,blood_group) VALUES (71,"Chelsea","Male","Fever, Cough, Cold","A+"),(72,"Hilary","Male","Headache","AB-"),(73,"Richard","Other","Stomachache","O+"),(74,"Camilla","Female","Fever","AB-"),(75,"Lars","Other","Headache","B+"),(76,"Sophia","Female","Headache","B+"),(77,"Kennan","Male","Constapation, Chest Pain, Stomachache","AB+"),(78,"Chava","Female","","B+"),(79,"Madaline","Other","Headache, Fever","B+"),(80,"Jonah","Female","","B+");
INSERT INTO patient (patient_id,name,gender,current_condition,blood_group) VALUES (81,"Judith","Male","Headache, Fever, Chest Pain, Constapation","AB+"),(82,"Ross","Other","Cough","A-"),(83,"Joy","Other","Chest Pain","B+"),(84,"Hannah","Other","Cough, Headache","B+"),(85,"Rigel","Male","Fever, Cough, Gastric, Chest Pain","B-"),(86,"Baker","Female","Cold","B-"),(87,"Orson","Female","Stomachache","A+"),(88,"Nerea","Other","Gastric","A+"),(89,"Jacob","Female","Stomachache, Fever","AB-"),(90,"Vielka","Other","Headache","O-");
INSERT INTO patient (patient_id,name,gender,current_condition,blood_group) VALUES (91,"Jayme","Other","","B-"),(92,"Selma","Male","","A+"),(93,"Solomon","Male","Cough, Cold, Fever, Stomachache","A-"),(94,"Kessie","Male","Fever, Constapation, Headache, Chest Pain","B-"),(95,"Elton","Female","Stomachache, Chest Pain, Constapation","AB-"),(96,"Martina","Female","Fever, Gastric, Headache, Cough","O-"),(97,"Venus","Female","Cough, Fever","AB+"),(98,"Ora","Other","Headache, Fever, Cough, Gastric","A+"),(99,"Chandler","Male","Chest Pain, Constapation, Stomachache","O-"),(100,"Odysseus","Female","Constapation, Cough, Stomachache","O+");
